### ISSUE TITLE
 Add some features to the CLI

### ISSUE THREAD

**Issue by code4you2021** [wxt-dev/wxt#369] opened 2024-01-25 01:02 UTC
### Feature Request

```bash

pnpx wxt@latest init <project-name> --with-src

pnpx wxt@latest init <project-name> --entry=options,test.contents

pnpx wxt@latest create --entry=options,test.contents

```
### Explanation

`pnpx wxt@latest init <project-name> --with-src`

When creating a project, use `src` as the root directory.

Currently, the process requires manual steps, which are cumbersome:
1. Create the `src` directory.
2. In the `wxt.config.ts` file, add `srcDir: "src"`.
3. Move the `assets`, `components`, `entrypoints`, and `public` files to the `src` directory.

---

`pnpx wxt@latest init <project-name> --entry=options,test.contents`

When creating a project, it should automatically generate contents, popup, and options pages.

Currently, the generated project defaults to only having a popup page. Creating contents and options pages requires manual intervention:

1. Create the `src` directory.
2. Manually create the contents page. If the content of the contents page is not remembered, users need to open the `https://wxt.dev` webpage, check the documentation, and copy the content to the `contents` page.

---

`pnpx wxt@latest create --entry=options,test.contents`

If the project already exists, use the command line to create the options page and `test contents` page.

**Comment by aklinker1** [comment] 2024-01-25 02:49
The `init` changes you recommend are a duplicate of #187, but in combination with your new `create` command, it's interesting.

It is definitely annoying to have to refer to the docs to add an entrypoint, and a code-gen tool would be useful, but that makes me think of Rails and I cringe on the inside 🫣

I don't want to maintain a code gen tool, TBH. Entrypoint boilerplate shouldn't be complicated enough that they need to be generated. For how rarely people create new projects, I don't think it's worth the extra work and continued maintenance.

Couple alternative solutions to the problems you're having:

- Create your own project template based on your preferences. I'd love to add community templates to the init section
- Create snippets for VSCode for creating entrypoint definitions. I'll probably create some of these and publish them at some point, this would be really useful

---

I really appreciate how much effort you put into this issue! I feel bad saying no, but since this project doesn't have any consistent contributors I can rely on yet, I have to decide what I'm willing to spend my time in 😓

**Closed** 2024-01-25 02:52 UTC
Labels: feature
