### ISSUE TITLE
please add externally_connectable property definition

### ISSUE THREAD

**Issue by honwhy** [wxt-dev/wxt#956] opened 2024-09-01 16:27 UTC
### add externally_connectable property to manifest definition

interface **WebExtensionManifest** lack of externally_connectable property

externally_connectable explains here, https://developer.chrome.com/docs/extensions/reference/manifest/externally-connectable

**Comment by aklinker1** [comment] 2024-09-03 19:10
Duplicate of #521

**Closed by aklinker1** 2024-09-03 19:10 UTC
Labels: duplicate, feature

**Comment by aklinker1** [comment] 2024-09-06 00:24
Released in [`v0.19.9`](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.9)

**Comment by aleclarson** [comment] 2025-02-08 18:02
Hi @aklinker1! 👋 

I think you closed this prematurely. There is still no `externally_connectable` property in WXT's `UserManifest` type. Proof here: https://github.com/search?q=repo%3Awxt-dev%2Fwxt%20externally_connectable&type=code

**Comment by aklinker1** [comment] 2025-02-12 06:07
@aleclarson Seems to work just fine? What version of WXT are you on?

<img width="707" alt="Image" src="https://github.com/user-attachments/assets/4a8af153-5f8a-4b95-9db8-499f3b964416" />

**Comment by aklinker1** [comment] 2025-02-12 06:07
Maybe you're experiencing #1116?
