### ISSUE TITLE
type error with ctx.addEventListener(document, "visibilitychange", activityDetected);

### ISSUE THREAD

**Issue by remusris** [wxt-dev/wxt#1246] opened 2024-12-03 22:55 UTC
### Describe the bug

Getting a type error when using this line below and a broken content script

`ctx.addEventListener(document, "visibilitychange", activityDetected);`

below is the rest of the code

```typescript
// entrypoints/content.ts
export default defineContentScript({
  matches: ["<all_urls>"],
  allFrames: true,
  
  main(ctx) {
    function activityDetected(event: Event) {
      if (event.type === "mousemove") {
        grabVideoTimecode();
      }
      
      browser.runtime.sendMessage({ action: "userActive", value: `${event.type}` });
    }

    function grabVideoTimecode() {
      const video = document.querySelector('video');
      if (video) {
        const currentTime = video.currentTime;
        browser.runtime.sendMessage({ 
          action: "videoTimecode", 
          value: currentTime.toFixed(2) 
        });
      } else {
        browser.runtime.sendMessage({ 
          action: "videoTimecode", 
          value: null 
        });
      }
    }

    // Add event listeners using the context to handle cleanup
    ctx.addEventListener(document, "mousemove", activityDetected);
    ctx.addEventListener(document, "keydown", activityDetected);    
    ctx.addEventListener(window, "blur", activityDetected);
    ctx.addEventListener(document, "visibilitychange", activityDetected);

    /* // Use regular DOM event listener for visibilitychange
    const visibilityHandler = (event: Event) => {
      activityDetected(event);
    };

    document.addEventListener("visibilitychange", visibilityHandler); */

    // Handle text selection and anchor tag detection
    ctx.addEventListener(document, "mouseup", () => {
      const selection = window.getSelection();
      if (!selection) return;
      
      const selectedText = selection.toString().trim();
      if (!selectedText) return;

      const range = selection.getRangeAt(0);
      let parentDiv = range.commonAncestorContainer as Node;
      
      while (parentDiv && (parentDiv as Element).nodeName?.toLowerCase() !== "div") {
        parentDiv = parentDiv.parentNode!;
      }

      if (parentDiv instanceof Element) {
        const anchorTag = parentDiv.querySelector("a");
        if (anchorTag) {
          anchorTag.style.backgroundColor = "yellow";
          console.log(`Found anchor: ${anchorTag.href}`);
        }
      }
    });

    // Clean up the visibilitychange listener when the content script is invalidated
    /* ctx.onInvalidated(() => {
      document.removeEventListener("visibilitychange", visibilityHandler);
    }); */
  }
});
``` 

This is the error

```
[{
    "resource": "/C:/Programming Content/memorylink_wxt_browser_extension/entrypoints/content.ts",
    "owner": "typescript",
    "code": "2345",
    "severity": 8,
    "message": "Argument of type '\"visibilitychange\"' is not assignable to parameter of type 'keyof WxtContentScriptEventMap'.",
    "source": "ts",
    "startLineNumber": 35,
    "startColumn": 36,
    "endLineNumber": 35,
    "endColumn": 54
}]
``` 

even though there's an example showing it works

even though there's an example showing it works

https://wxt.dev/api/reference/wxt/client/classes/ContentScriptContext.html#example

### Reproduction

code is above

### Steps to reproduce

run this code in the content script

```typescript
// entrypoints/content.ts
export default defineContentScript({
  matches: ["<all_urls>"],
  allFrames: true,
  
  main(ctx) {
    function activityDetected(event: Event) {
      if (event.type === "mousemove") {
        grabVideoTimecode();
      }
      
      browser.runtime.sendMessage({ action: "userActive", value: `${event.type}` });
    }

    function grabVideoTimecode() {
      const video = document.querySelector('video');
      if (video) {
        const currentTime = video.currentTime;
        browser.runtime.sendMessage({ 
          action: "videoTimecode", 
          value: currentTime.toFixed(2) 
        });
      } else {
        browser.runtime.sendMessage({ 
          action: "videoTimecode", 
          value: null 
        });
      }
    }

    // Add event listeners using the context to handle cleanup
    ctx.addEventListener(document, "mousemove", activityDetected);
    ctx.addEventListener(document, "keydown", activityDetected);    
    ctx.addEventListener(window, "blur", activityDetected);
    ctx.addEventListener(document, "visibilitychange", activityDetected);

    /* // Use regular DOM event listener for visibilitychange
    const visibilityHandler = (event: Event) => {
      activityDetected(event);
    };

    document.addEventListener("visibilitychange", visibilityHandler); */

    // Handle text selection and anchor tag detection
    ctx.addEventListener(document, "mouseup", () => {
      const selection = window.getSelection();
      if (!selection) return;
      
      const selectedText = selection.toString().trim();
      if (!selectedText) return;

      const range = selection.getRangeAt(0);
      let parentDiv = range.commonAncestorContainer as Node;
      
      while (parentDiv && (parentDiv as Element).nodeName?.toLowerCase() !== "div") {
        parentDiv = parentDiv.parentNode!;
      }

      if (parentDiv instanceof Element) {
        const anchorTag = parentDiv.querySelector("a");
        if (anchorTag) {
          anchorTag.style.backgroundColor = "yellow";
          console.log(`Found anchor: ${anchorTag.href}`);
        }
      }
    });

    // Clean up the visibilitychange listener when the content script is invalidated
    /* ctx.onInvalidated(() => {
      document.removeEventListener("visibilitychange", visibilityHandler);
    }); */
  }
});
``` 

### System Info

```shell
[{
    "resource": "/C:/Programming Content/memorylink_wxt_browser_extension/entrypoints/content.ts",
    "owner": "typescript",
    "code": "2345",
    "severity": 8,
    "message": "Argument of type '\"visibilitychange\"' is not assignable to parameter of type 'keyof WxtContentScriptEventMap'.",
    "source": "ts",
    "startLineNumber": 35,
    "startColumn": 36,
    "endLineNumber": 35,
    "endColumn": 54
}]
```
```


### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment] 2024-12-03 23:04
I could reproduce the type error, but your report on discord said it didn't work at runtime as well. That I couldn't reproduce.

```ts
export default defineContentScript({
  matches: ['*://*.google.com/*'],
  main(ctx) {
    ctx.addEventListener(document, 'visibilitychange', (test) => {
      console.log('test', test);
    });
  },
});
```

This reports a type error, but if ignored, code runs just fine in the browser. The test log gets printed when switching between tabs.

Can also confirm that the type problem has been fixed by https://github.com/wxt-dev/wxt/pull/1245

Gonna mark this as missing reproduction since I couldn't reproduce your runtime problem. Please provide a full, minimal reproduction if #1245 doesn't fix this. That's a full project; a zip uploaded in a comment or a github repo, not copy-pasted code.

**Closed by aklinker1** 2024-12-03 23:04 UTC
Labels: pending-triage

**Comment by remusris** [comment] 2024-12-03 23:14
Here is the code

https://github.com/remusris/fresh-wxt-plate

pnpm install

uncomment this line here

`ctx.addEventListener(document, "visibilitychange", activityDetected);`

and you don't get any console.logs

comment it and you get console.logs to fire

this one right here

`console.log(`activityDetected: ${event.type}`);`

**Comment by aklinker1** [comment] 2024-12-04 04:10
Thank you, checking it out now!

**Comment by aklinker1** [comment] 2024-12-04 04:14
Works just fine? Switching tabs causes it to fire

https://github.com/user-attachments/assets/b3ff458a-837b-4d8a-a7a2-bec902fdc9ae
