### ISSUE TITLE
`--user-data-dir` not work in Windows10 , same to #586

### ISSUE THREAD

**Issue by slow-groovin** [wxt-dev/wxt#1132] opened 2024-11-01 09:21 UTC
### Describe the bug

When setting `--user-data-dir`  to persist config, it didn't work,
the target dir is empty after start and exit dev.
It's same to #586,  two `--user-data-dir` appears twice in `chrome://version/` Command Line, and the first have effect

![image](https://github.com/user-attachments/assets/fe1c31e0-50ef-42ec-8f2e-c776fbf6a732)

### Reproduction

same to #586
```
export default defineRunnerConfig({
	// On Windows, the path must be absolute
	chromiumArgs: [
		`--user-data-dir=D:\\slow-groovin\\Documents\\wxt-learn\\.wxt\\chrome-data`,
		`--lang=en`
	],
});
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 
    Memory: 12.99 GB / 30.69 GB
  Binaries:
    Node: 22.10.0 - D:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.3 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by only-issues** [comment] 2024-11-06 09:32
+1

**Comment by Dollyn** [comment] 2024-11-12 10:23
after dig into the code, find out that  it did work, but not as sample as the doc said.

without the keepProfileChanges: true flag,  web-ext-run  will **copy** the dir you spicified with `--user-data-dir` to a temp dir and use that temp dir every time on start.

so if you want to use a seperate dir as chrome profile, and prevent settings lost every time  on start, 
the following config will work.

```
export default defineRunnerConfig({
  startUrls: ['https://google.com'],
  keepProfileChanges: true,
  chromiumProfile: "C:\\Users\\xxx\\yyy\\chrome-data",
  chromiumArgs: ['--window-size=1024,800', "--auto-open-devtools-for-tabs", "--devtools-flags currentDockState=bottom"],
});
```

BTW,
that leed to another  issue, some chrome preferences will be reset every time, because of chrome-launcher issue/feature:
https://github.com/GoogleChrome/chrome-launcher/issues/335.
they use a sample/fake merge method  with existing prefs`         this.fs.writeFileSync(preferenceFile, JSON.stringify({...content, ...this.prefs}), 'utf-8');
`
and on unfortunately, web-ext-run hard coded a default pref:
```
const DEFAULT_PREFS = {
  'extensions.ui.developer_mode': true
};
```
so chrome prefs start with 'extensions.' will lost.

**Comment by aklinker1** [comment] 2024-11-18 01:26
Gonna close this as a duplicate of https://github.com/wxt-dev/wxt/issues/1023, seems to be the same problem.

**Closed by aklinker1** 2024-11-18 01:26 UTC
Labels: bug, duplicate
