### ISSUE TITLE
content script ui debug experience is very bad

### ISSUE THREAD

**Issue by pftom** [wxt-dev/wxt#687] opened 2024-05-31 15:04 UTC
### Describe the bug

when content script ui report error, no any error will show, just cannot load content js files:

![image](https://github.com/wxt-dev/wxt/assets/26423749/158e333f-7ff6-4baf-a113-6e41d286bdc9)
![image](https://github.com/wxt-dev/wxt/assets/26423749/0e7598cd-e529-4c4a-9c2d-aa970a2258b9)

any config for better detail error msg?

### Reproduction

use content ui
add some js error for content ui, then content ui can't show but without any error details

### System Info

```shell
nodejs: v20.11.1
wxt: 0.16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pftom** [comment] 2024-06-03 02:52
@aklinker1 I see the code , the build error cause is not prompt
<img width="881" alt="image" src="https://github.com/wxt-dev/wxt/assets/26423749/11fd63a8-3d27-4d09-afc1-663f07275968">

**Comment by aklinker1** [comment] 2024-06-03 05:12
Hmm, I noticed the other day that consola doesn't log an error's `cause`, that could be why it doesn't show up

**Comment by aklinker1** [comment] 2024-06-17 19:55
Coming back to this, the problem is that the content script isn't loading at all, not sure what I was thinking before.

I think this is a duplicate of https://github.com/wxt-dev/wxt/issues/353, so I'm going to close it.

**Closed by aklinker1** 2024-06-17 19:55 UTC
Labels: pending-triage
