### ISSUE TITLE
@vue/devtools is not work well with wxt

### ISSUE THREAD

**Issue by neilfranci** [wxt-dev/wxt#345] opened 2024-01-14 08:40 UTC
### Describe the bug

I'm trying to use @vue/devtools from this setup:
https://devtools-next.vuejs.org/guide/standalone
but  it keeps throwing an error whenever I `pnpm i` or `pnpm dev`

Popup still worked with just add `<script....` tag

### To Reproduce
[dev-tools.zip](https://github.com/wxt-dev/wxt/files/13930810/dev-tools.zip)

Steps to reproduce the bug using the reproduction:

1. Uncomment `//devtools.connect("http://localhost", 8098);` in `content/index.ts`
2. Install dependencies: `pnpm i` => **Error**
3.  Even if comment out the line and `pnpm i` worked, run `pnpm dev` still give the **error**

### Screenshots

![image](https://github.com/wxt-dev/wxt/assets/66520542/4597ed24-1748-42ee-a1a8-46f27c3a4f67)

### Environment
```
  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 6.83 GB / 15.73 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    wxt: ^0.14.1 => 0.14.1 
```

**Comment by aklinker1** [comment] 2024-01-14 14:35
JS entrypoints can't have side-effects outside the main function. Just move the `devtools.connect` call inside the `main` function, and it works:

```diff
import { devtools } from "@vue/devtools";

-devtools.connect("http://localhost", 8098);
export default defineContentScript({
  // Set manifest options
  matches: ["<all_urls>"],

  main(ctx) {
+   devtools.connect("http://localhost", 8098);
    console.log("Hello content!", { id: browser.runtime.id });
  },
});
```

Duplicate of https://github.com/wxt-dev/wxt/issues/336. I need to improve the error message for this, and document it.

**Closed** 2024-01-14 15:36 UTC
Labels: docs, duplicate

**Comment by aklinker1** [comment] 2024-01-16 20:11
Released new warning in https://github.com/wxt-dev/wxt/releases/tag/v0.14.2
