### ISSUE TITLE
ERROR  Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by dongnaebi** [wxt-dev/wxt#367] opened 2024-01-23 15:57 UTC
### Describe the bug

I followed the guide to try out wxt, but when I added a content script, dev threw an error as soon as it ran. 
```
 ERROR  Cannot read properties of undefined (reading 'forEach') 
```

I couldn't figure out what the problem was or how to continue. Did I miss something?

### To Reproduce

[wxt-demo.zip](https://github.com/wxt-dev/wxt/files/14026781/wxt-demo.zip)

1. Install dependencies: `pnpm i`
2. Start dev mode: `pnpm dev`

### Expected behavior

-

### Screenshots

![image](https://github.com/wxt-dev/wxt/assets/6902417/23be0fec-a670-4f65-8252-576a1f49f43c)

### Environment

```
  System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz
    Memory: 4.14 GB / 15.84 GB
  Binaries:
    Node: 18.19.0 - ~\.nvmd\versions\18.19.0\node.EXE
    npm: 10.2.3 - ~\.nvmd\versions\18.19.0\npm.CMD
    pnpm: 8.12.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    wxt: ^0.14.0 => 0.14.5 
```

**Comment by dvlden** [comment] 2024-01-23 21:56
Perhaps the docs require an update, but TS prompts me in your demo that you need to provide `matches` property inside of your `example-ui.content.ts`

**Comment by aklinker1** [comment] 2024-01-23 22:35
@dvlden is correct. Perhaps we should add validation, TS isn't enough if misconfigured or if you're using JS.

I don't think vite or nuxt include validation outside TS.

**Comment by aklinker1** [comment] 2024-01-23 22:38
Did the error message not print a stack trace? That should have pointed you to `matches` being required.

**Comment by aklinker1** [comment] 2024-01-24 04:18
Interesting, `wxt build` passes, but just doesn't assign a value to `matches` in the manifest. That should be fixed as well. Probably need validation for that to work.

**Comment by aklinker1** [comment] 2024-01-24 04:20
It does output a stacktrace, but the bundled code doesn't make it very clear exactly what is wrong. It does mention `matches`, and there's enough context for me to recognize what the issue is, but probably not to everyone else. I'll add some basic validation.

<img width="1084" alt="Screenshot 2024-01-23 at 10 18 56 PM" src="https://github.com/wxt-dev/wxt/assets/10101283/05dddc4b-7085-4b28-a877-89fd72d7ec91">

**Closed** 2024-01-24 06:31 UTC
Labels: triage

**Comment by aklinker1** [comment] 2024-01-24 06:42
Validation messages added in https://github.com/wxt-dev/wxt/releases/tag/v0.14.6

**Comment by dongnaebi** [comment] 2024-01-24 11:14
Sorry for not replying sooner with more information. The speed of this fix is amazing!

I think we should also update the docs, since the hello world example is very important for beginners.

https://wxt.dev/guide/content-script-ui.html

**Comment by aklinker1** [comment] 2024-01-24 14:00
Ahh, OK, that's where you're coming from. I've updated the docs: https://github.com/wxt-dev/wxt/commit/dab8efa140192da87decfbf97f63bbaeaa9303f5
