### ISSUE TITLE
Persist data not working (Windows11, Chrome)

### ISSUE THREAD

**Issue by placoderm** [wxt-dev/wxt#1023] opened 2024-10-01 19:30 UTC
### Describe the bug

I'm reading through the new docs and am trying to implement [persist-data](https://deploy-preview-933--creative-fairy-df92c4.netlify.app/guide/essentials/config/browser-startup.html#persist-data)

I have this in my web-ext.config.ts file (which is in my root):

```ts
// web-ext.config.ts
export default defineRunnerConfig({
  chromiumArgs: ["--user-data-dir=./.wxt/chrome-data"],
});
```

I saved, restarted VSCode and ran pmpm dev. There was no new directory added to .wxt for /chrome-data/

I installed a plugin in the dev launched Chrome, cancelled the dev, restarted everything, and the plugin was not there.

Please see the discussion on https://discord.com/channels/1212416027611365476/1290064175791472670

_**This problem seems to be exclusive to Windows.**_

### Reproduction

I also tried:

```ts
// wxt.config.ts
export default defineConfig({
  runner: { chromiumArgs: ["--user-data-dir=./.wxt/chrome-data"] },
});
```
Still with no success.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 2.78 GB / 15.33 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.11.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
    Chrome: Version 129.0.6668.71 (Official Build) (64-bit)
  npmPackages:
    wxt: ^0.19.1 => 0.19.10
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment] 2024-10-02 14:01
Thanks for the report. If anyone has windows and can try to reproduce this, I'd appreciate this. It works on Linux and Mac.

**Comment by Judimax** [comment] 2024-10-02 19:04
Greetings I can conform that this is the case as well on my windows computer

**Comment by aklinker1** [comment] 2024-10-02 23:51
@Judimax Can you try and launch Chrome directly and mess around with the CLI flags to see if you can find something that stores chrome data in a different directory?

```sh
chrome.exe --user-data-dir=chrome-data
```

**Comment by Judimax** [comment] 2024-10-02 23:56
im in the discord if you want to hop on a call to debug?

**Comment by 1natsu172** [comment] 2024-10-03 07:10
@placoderm @Judimax _kdme_ that windows user, has posted something like this before, which may help to solve something.

- https://discord.com/channels/1212416027611365476/1268068051874742312/1268499442831724676
- https://discord.com/channels/1212416027611365476/1270035277087248457/1270648007800520705

**Comment by Judimax** [comment] 2024-10-03 10:45
Greetings this seems to only work for Profile 1 any other profile I get, and Profile 1 seems to be a dummy profile of sorts
 ERROR  connect ECONNREFUSED 127.0.0.1:58396                                                        6:45:35 a.m.  

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)

**Comment by aklinker1** [comment] 2024-10-03 16:50
> im in the discord if you want to hop on a call to debug?

@Judimax Sorry, was checking in on things before I went to bed.

That said, I forgot that I had a windows VM on my work computer, so I played around. First try got it working:

```sh
chrome.exe --user-data-dir="C:\\Users\Username\Downloads\chrome-data"
```

And it worked just fine. `C:\\Users\Username\Downloads\chrome-data` did NOT exist beforehand, chrome created it when it started up.

Also tried with a relative path, as shown in the example:

```sh
"C:\Program Files\Google\Chrome\Application\chrome.exe" --user-data-dir=".\.wxt\chrome-data"
```

But this doesn't work. It shows an alert when starting up that "Google Chrome cannot read and write to its data directory: .\.wxt\chrome-data"

Same error with and without the leading ".\". Also throws the error if I create the .wxt directory and the .wxt/chrome-data directory.

However, it does work if I use an absolute path:

```sh
"C:\Program Files\Google\Chrome\Application\chrome.exe" --user-data-dir="C:\Users\Username\Downloads\test\.wxt\chrome-data"
```

So it appears the only requirement is you use an absolute path. And I put it in quotes just to be safe.

---

That means this should work for windows users:

```ts
// web-ext.config.ts
import { resolve } from 'node:path';

export default defineRunnerConfig({
  chromiumArgs: [`--user-data-dir="${resolve(".wxt/chrome-data")}"`
});
```

I will update the docs

**Comment by placoderm** [comment] 2024-10-03 20:20
```
  chromiumArgs: [`--user-data-dir="${resolve(".wxt/chrome-data")}"`],
```

So that didn't work for me. Here is my `web-ext.config.ts:

```
import { defineRunnerConfig } from "wxt";
import { resolve } from "node:path";

export default defineRunnerConfig({
  chromiumArgs: [`--user-data-dir="${resolve(".wxt/chrome-data")}"`],
});
```

When I run that the profile that chrome uses is still here:

`C:\Users\learn\AppData\Local\Temp\tmp-web-ext--13824-DkSV2bod0aOw\Default`

I try adding bookmarks to the bookmark bar and starting again. When I restart they are gone.

**Comment by aklinker1** [comment] 2024-10-03 23:12
@placoderm can you try quitting chrome completely from the task manager before running the command?

Also, try running Chrome directly: 

```sh
"C:\Program Files\Google\Chrome\Application\chrome.exe" --user-data-dir="C:\Users\Username\Downloads\test\.wxt\chrome-data"
```

**Comment by placoderm** [comment] 2024-10-03 23:46
When I run in chrome directly as you suggest it works, creating a new profile. Running again, it goes to that same profile.

I tried quitting chrome from taskmanager and running with 
```
  chromiumArgs: [`--user-data-dir="${resolve(".wxt/chrome-data")}"`],

```

in `web-ext.config.ts`. Still didn't work.

I copied the `chrome-data` the commandline created in the downloads folder to the `.wxt` folder in my project. Still didn't use that.

**Comment by aklinker1** [comment] 2024-10-03 23:50
> I copied the chrome-data the commandline created in the downloads folder to the .wxt folder in my project. Still didn't use that.

Wait, hold on, so it did create a `chrome-data` folder at some point?

**Comment by placoderm** [comment] 2024-10-03 23:52
> Wait, hold on, so it did create a `chrome-data` folder at some point?

Yes, when I did this on the command line:
```
"C:\Program Files\Google\Chrome\Application\chrome.exe" --user-data-dir="C:\Users\Username\Downloads\test\.wxt\chrome-data"
```

As expected it created a new profile and launched chrome. Sorry that wasn't more clear.

**Comment by aklinker1** [comment] 2024-10-04 00:13
OK, can you run `wxt --debug` and share the output? Make sure to keep 

```
chromiumArgs: [`--user-data-dir="${resolve(".wxt/chrome-data")}"`],
```

in your config file. You can ctrl+C out of the command once the browser opens. Specifically, there should be a section at the very bottom containing the web-ext config. something like this:

```
⚙ web-ext config: { console: undefined,                                                                    7:12:35 PM
  devtools: undefined,
  startUrl: [ 'https://duckduckgo.com' ],
  keepProfileChanges: undefined,
  chromiumBinary: undefined,
  chromiumProfile: undefined,
  chromiumPref: { devtools: { synced_preferences_sync_disabled: [Object] } },
  args: undefined,
  target: 'chromium',
  sourceDir:
   '/home/aklinker1/Development/github.com/wxt-dev/wxt/packages/wxt-demo/.output/chrome-mv3',
  noReloadManagerExtension: true,
  noReload: true,
  noInput: true }
⚙ web-ext options: { shouldExitProgram: false }
```

**Comment by placoderm** [comment] 2024-10-04 00:30
Here you go…
```
⚙ web-ext config: { console: undefined,                                               1:26:41 PM
  devtools: undefined,
  startUrl:
   [ 'https://suttacentral.net',
     'https://suttacentral.net/mn82/en/sujato',
     'https://discourse.suttacentral.net/t/mn25-absent-from-bh-bodhis-classes/36183' ],
  keepProfileChanges: undefined,
  chromiumBinary: undefined,
  chromiumProfile: undefined,
  chromiumPref: { devtools: { synced_preferences_sync_disabled: [Object] } },
  args:
   [ '--user-data-dir="C:\\Users\\learn\\Videos\\PROJECTS\\SC-plugin-parts\\SuttaCentral-Enhancement-Extension\\.wxt\\chrome-data"' ],
  target: 'chromium',
  sourceDir:
   'C:\\Users\\learn\\Videos\\PROJECTS\\SC-plugin-parts\\SuttaCentral-Enhancement-Extension\\.output\\chrome-mv3',
  noReloadManagerExtension: true,
  noReload: true,
  noInput: true }
⚙ web-ext options: { shouldExitProgram: false }                                       1:26:41 PM   
✔ Opened browser in 795 ms                                                            1:26:41 PM   
```

And here is my exact `web-ext.config.ts`:
```
import { defineRunnerConfig } from "wxt";
import { resolve } from "node:path";

export default defineRunnerConfig({
  startUrls: ["https://suttacentral.net", "https://suttacentral.net/mn82/en/sujato", "https://discourse.suttacentral.net/t/mn25-absent-from-bh-bodhis-classes/36183"],
  chromiumArgs: [`--user-data-dir="${resolve(".wxt/chrome-data")}"`],
});

```

**Comment by aklinker1** [comment] 2024-10-04 12:30
Huh, alright yeah, no idea why it doesn't work for you. That all looks good. It's clearly using an absolute path, and WXT is properly passing the arguments through to web-ext.

**Comment by placoderm** [comment] 2024-10-04 17:39
I will post on Discord and see if there is a windows user there who can test.

**Comment by 1natsu172** [comment] 2024-10-04 18:03
@aklinker1 Why don't you pass the example zip you are testing to @placoderm ? You two are not working on the same reproduction, right? Just to be safe, the less difference the better for debug.

**Comment by breadgrocery** [comment] 2024-10-17 04:18
`chromium.js` in **web-ext-run**:
```js
  let {
    userDataDir,
    profileDirName
  } = await ChromiumExtensionRunner.getProfilePaths(this.params.chromiumProfile);
```
So this works, but it requires that the specified directory already exists:
```js
  runner: {
    ...
    chromiumProfile: "D:\\chrome-profile",
    ...
  },
```

**Comment by szymski** [comment] 2024-11-01 20:48
I had a similar problem with configuring persistence in Google Chrome on Windows 11. What the docs are saying currently seems to be totally irrelevant.
What worked for me is this (in web-ext.config.ts file):
```ts
import { resolve } from 'node:path';
import { defineRunnerConfig } from 'wxt';

export default defineRunnerConfig({
    chromiumProfile: `${resolve('.wxt/chrome-data')}`,
});
```
Only `chromiumProfile` needs to be set as the target directory for configs. That's it. Nothing else is requried. Hope it helps anybody :)

**Comment by kmanev073** [comment] 2024-11-21 22:47
I can confirm this combination works on Windows 11:

```
export default defineRunnerConfig({
    chromiumProfile: `${resolve('.wxt/chrome-data')}`,
    keepProfileChanges: true,
});
```

You need keepProfileChanges set to true otherwise the profile is new everytime chrome is started.

**Comment by aklinker1** [comment] 2024-11-22 14:53
Alright, I've updated the docs. Gonna close this now that we've found a solution.

**Closed by aklinker1** 2024-11-22 14:53 UTC
Labels: bug, contribution welcome

**Comment by placoderm** [comment] 2024-11-22 17:54
Thanks for all your hard work!
