### ISSUE TITLE
import.meta not supported inside wxt.config.ts file

### ISSUE THREAD

**Issue by minht11** [wxt-dev/wxt#934] opened 2024-08-21 14:16 UTC
### Describe the bug

Try using `import.meta.dirname` inside `wxt.config.ts` file.

```
✖ Command failed after 96 ms                                                                                            5:14:37 PM

 ERROR  Cannot use 'import.meta' outside a module                                                                        5:14:37 PM

  import.meta.dirname;
  ^^^^
  
  SyntaxError: Cannot use 'import.meta' outside a module
  at new Script (node:vm:99:7)
  at createScript (node:vm:255:10)
  at Object.runInThisContext (node:vm:303:10)
```

### Reproduction

Use `import.meta.dirname` inside `wxt.config.ts` file.

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 77.20 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.proto/shims/node
    Yarn: 1.22.22 - ~/.proto/shims/yarn
    npm: 10.2.4 - ~/.proto/shims/npm
    pnpm: 9.6.0 - ~/.proto/shims/pnpm
  Browsers:
    Brave Browser: 126.1.67.123
    Chrome: 127.0.6533.120
    Chrome Canary: 130.0.6669.0
    Edge: 127.0.2651.105
    Safari: 17.6
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment] 2024-08-21 14:51
Duplicate of #297. The file is loaded as this weird CJS/ESM hybrid, and it doesn't support all ESM features, like `import.meta.dirname`.

Use `__dirname` instead.

**Closed** 2024-08-21 14:53 UTC
Labels: duplicate
