### ISSUE TITLE
I get error when loading content script: "Cannot find anchor"

### ISSUE THREAD

**Issue by ddeisadze** [wxt-dev/wxt#445] opened 2024-02-14 19:45 UTC
I am using the default template see:

```
import './style.css';

export default defineContentScript({
  matches: ['<all_urls>'],
  // 2. Set cssInjectionMode
  cssInjectionMode: 'ui',

  async main(ctx) {
    // 3. Define your UI
    const ui = await createShadowRootUi(ctx, {
      name: 'example-ui',
      anchor: '#anchor',
      position: 'inline',
      onMount(container) {
        // Define how your UI will be mounted inside the container
        const app = document.createElement('p');
        app.textContent = 'Hello world!';
        container.append(app);
      },
    });

    // 4. Mount the UI
    ui.mount();
  },
});
```

But i get this error when I run: 

<img width="783" alt="image" src="https://github.com/wxt-dev/wxt/assets/1585369/c310e341-e840-4129-bbe3-4c1725b6d32c">

I am expecting a shadow root to be created but its not.

**Comment by ddeisadze** [comment] 2024-02-14 19:50
Also I just checked the manifest, content_script is not populated, see:

```
{
  "manifest_version": 3,
  "name": "@scoutahead/extension-new",
  "description": "manifest.json description",
  "version": "0.0.0",
  "icons": {
    "16": "icon/16.png",
    "32": "icon/32.png",
    "48": "icon/48.png",
    "96": "icon/96.png",
    "128": "icon/128.png"
  },
  "commands": {
    "wxt:reload-extension": {
      "description": "Reload the extension during development",
      "suggested_key": {
        "default": "Alt+R"
      }
    }
  },
  "background": {
    "service_worker": "background.js"
  },
  "action": {
    "default_title": "Default Popup Title",
    "default_popup": "popup.html"
  },
  "host_permissions": [
    "<all_urls>",
    "http://localhost/*"
  ],
  "content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval' http://localhost:3000; object-src 'self';"
  },
  "permissions": [
    "tabs",
    "scripting"
  ]
}
```

**Comment by aklinker1** [comment] 2024-02-14 20:25
Duplicate of https://github.com/wxt-dev/wxt/issues/434#issuecomment-1935399083.

`anchor: "#anchor"` is a query selector used as an example. You need to fill it out with your own query selector, or remove the option if you just want to add it to the body.

As for the manifest not containing the content script, in dev mode they're registered dynamically at runtime so they can be reloaded on change. See https://github.com/wxt-dev/wxt/issues/434#issuecomment-1934830092 for more details.

Since this is the second time someone has had this problem, I'll update the example to use `#your-anchor-query-selector` instead of just `#anchor`.

**Closed** 2024-02-14 20:26 UTC
Labels: duplicate

**Comment by aklinker1** [comment] 2024-02-14 20:44
I've updated the docs: see https://github.com/wxt-dev/wxt/commit/a0d16430219c9c90f8733f12229ebf665c64f005 and https://github.com/wxt-dev/wxt/commit/a0d16430219c9c90f8733f12229ebf665c64f005
