### ISSUE TITLE
Pre-transform error: Failed to load url /popup.js

### ISSUE THREAD

**Issue by yunsii** [wxt-dev/wxt#465] opened 2024-02-20 08:18 UTC
### Describe the bug

It looks like popup page works as expected, but the console still print `Pre-transform error: Failed to load url /popup.js`

![image](https://github.com/wxt-dev/wxt/assets/18096089/b5cbb503-4631-4426-ae1a-4e7e6e9f69fd)

### To Reproduce

https://github.com/yunsii/wxt-reproduction

Steps to reproduce the bug using the reproduction:

1. Install dependencies: `pnpm i`
2. Start dev mode: `pnpm dev`

### Expected behavior

Is it a wrong log print?

### Environment

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 22.84 GB / 31.35 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
    pnpm: 8.14.0 - ~/.nvm/versions/node/v18.4.0/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.85
  npmPackages:
    wxt: ^0.16.8 => 0.16.8
```

**Comment by aklinker1** [comment] 2024-02-20 14:15
Duplicate of #421, closing in favor of it. Thanks for the extra info 👍

**Closed by aklinker1** 2024-02-20 14:15 UTC
Labels: bug, duplicate
