### ISSUE TITLE
Content script is reloaded twice when the file is saved.

### ISSUE THREAD

**Issue by kazu-ux** [wxt-dev/wxt#938] opened 2024-08-28 08:20 UTC
### Describe the bug

Content script is reloaded twice when the file is saved.

### Reproduction

https://github.com/user-attachments/assets/433eb77a-6924-435d-bdd5-04a8a899d7f9

### Steps to reproduce

Run `npm install` followed by `npm run dev`

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 AMD Ryzen 5 3400G with Radeon Vega Graphics 

    Memory: 1.61 GB / 13.94 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.9.0 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.10 - ~\AppData\Local\reflex\bun\bin\bun.EXE     
    Watchman: 20230806.083715.0 - D:\watchman\bin\watchman.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    wxt: ^0.19.7 => 0.19.7
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment] 2024-08-29 12:23
<details>
<summary>Can't reproduce:</summary>

https://github.com/user-attachments/assets/5fab4a7f-24b1-4f0c-976d-c6bb03b536c6

</details>

Can you apply this patch and share the logs?

```diff
diff --git a/node_modules/wxt/dist/core/create-server.mjs b/node_modules/wxt/dist/core/create-server.mjs
index 30688b19352a3c5df0a99ae3526f92952d375cd3..7d3db3668d23d0cecdd2db550901185b5bb0c861 100644
--- a/node_modules/wxt/dist/core/create-server.mjs
+++ b/node_modules/wxt/dist/core/create-server.mjs
@@ -102,6 +102,7 @@ function createFileReloader(server) {
     changeQueue.push([event, path]);
     await fileChangedMutex.runExclusive(async () => {
       if (server.currentOutput == null) return;
+      console.log(changeQueue);
       const fileChanges = changeQueue.splice(0, changeQueue.length).map(([_, file]) => file);
       if (fileChanges.length === 0) return;
       await wxt.reloadConfig();

```

**Comment by aklinker1** [comment] 2024-08-30 08:36
Hmm, not what I expected. It seems like VS Code is saving the file multiple times, and slow enough that my current debouncing logic isn't considering it a single save.

On my side, the only thing I could do is increase the delay, or replace the current logic with a real throttle. But I haven't seen anyone else with this error, so I'd like to figure out why it's happening to you first.

Do you have any plugins installed that would be causing this? Can you restart vscode and open it with extensions disabled to see if that's the problem?

```sh
code --disable-extensions path/to/your-project
```

**Comment by kazu-ux** [comment] 2024-08-30 11:59
I tried creating a new profile and disabling extensions, but the issue still persists.

https://github.com/user-attachments/assets/bdb50dce-efaf-408f-842a-10abc126be11

**Comment by 1natsu172** [comment] 2024-08-30 18:24
Hmm, I was able to reproduce this. Sometimes I got multiple “changed” logs. It happens sometimes when saved(⌘+S)  once every 3sec by feel. Doesn't seem to be caused by personal something tool, it occurs in both `npm` and `pnpm` with  `VSCode` and `TextEdit.app`

**Comment by 1natsu172** [comment] 2024-08-30 19:02
Nah, if I look closely at…it's a bit different from his. He has [`Changed:` -> `Reloaded:`] x3, but I have multiple `Changed:` and `Reloaded:` is not shown after that. 🤷

**Comment by 1natsu172** [comment] 2024-08-31 04:01
@kazu-ux The difference between our environment and yours is that Windows/MacOS and you are using different disk drives `C:`&`D:` (I noticed it).

And I found the Windows drive issue in Chokidar https://github.com/paulmillr/chokidar/issues/665 - does the problem continue when you run WXT on the `C:` drive?

**Comment by kazu-ux** [comment] 2024-09-07 05:53
The same issue occurred on the C drive.

**Comment by 1natsu172** [comment] 2024-09-07 07:19
@kazu-ux Okay, once you said that it does not reproduce in Notepad, is it 100% ? If so, we can say the problem isn't with chokidar. Because in the video you posted with the `code --disable-extensions`, the problem isn't happening at “Hello content. 2” and the timing is causing the problem at “Hello content. 3”. So the problem may in fact occur with Notepad if you try it many times.

**Comment by kazu-ux** [comment] 2024-09-07 08:20
Yes, I edited the code 50 times in Notepad, but no issues occurred.

**Comment by 1natsu172** [comment] 2024-09-07 11:19
@kazu-ux Thanks for many tried. So…it may as I thought, be a VSCode issue or that with the VSCode's integrated terminal. We can only suspect VSCode settings, but what happens if you try set `.output` dir to the `Files: Watcher Exclude` and disable to `TypeScript > TsServer > Experimental: Use Vs Code Watcher` with workspace settings?

You could add the below code to `.vscode/settings.json`, or set up in the GUI.

```json
{
  "files.watcherExclude": {
    "**/.output/**": true
  },
  "typescript.tsserver.experimental.useVsCodeWatcher": false
}
```

I can only think that something primitive in VSCode is the cause.

**Comment by kazu-ux** [comment] 2024-09-09 22:29
I changed settings. but the issue still persists.

I noticed that it works properly when I edit the popup code.

https://github.com/user-attachments/assets/ae04ce6e-6278-44b6-8ecb-ce3e0ba1e690

**Comment by 1natsu172** [comment] 2024-09-10 16:31
So weird, reloading popup and content-script have different methods, but I don't know why it would make a difference with that and the editor. 🤷

**Comment by aklinker1** [comment] 2024-09-10 21:35
I'm torn on what to do here.

1. Leave it as-is, queuing up file changes that occur while rebuilding
2. Debounce the file saves by ~100ms (or longer) so if a second save happens in that timeframe, it doesn't trigger a rebuild
3. Ignore all file changes until the build is finished

Thoughts on option 2? That's my preferred solution

**Comment by 1natsu172** [comment] 2024-09-11 01:32
@aklinker1 Yes, I think option 2 is the best if we try to tune it up. Chokidar has many performance options, but too complicated lol. https://github.com/paulmillr/chokidar#performance

Do we use `awaitWriteFinish` or debounce on the WXT side to the extent that performance does not degrade? Or, we can't cover all environments, so provide a watcher performance options with an `wxt.config.ts`.

**Comment by aklinker1** [comment] 2024-09-11 18:54
Didn't know about that option... Could be a solution as well.

The other option is to wait for the v4 rewrite they're in the middle of.

You can already pass in the watcher options via vite - WXT doesn't have its own file watcher

**Comment by aklinker1** [comment] 2024-09-11 18:55
> You can already pass in the watcher options via vite - WXT doesn't have its own file watcher

Actually, that might be wrong. I need to double check the code

**Comment by 1natsu172** [comment] 2024-09-12 02:44
> Actually, that might be wrong. I need to double check the code

Yep, we can actually pass it via vite config. But currently the user side values isn't merged with the default WXT side values in `getBaseConfig`. So it's fragile now.

https://github.com/wxt-dev/wxt/blob/aedbba3f3d5c87684d9d6907a8c1e7a5df534208/packages/wxt/src/core/builders/vite/index.ts#L38

> The other option is to wait for the v4 rewrite they're in the middle of.

I was thinking too. I just don't know if v4 will change the performance aspect. Looking at the current v4 branch, it looks like the main focus is TSing and getting rid of dependencies.

And vite is discussing about watcher with chokidar for a long time lol. https://github.com/vitejs/vite/issues/13593

**Comment by 1natsu172** [comment] 2024-09-12 02:51
Maybe we should follow the chokidar v4 and vite movement and only ready the stable passing watcher option in place until then.

**Comment by aklinker1** [comment] 2024-09-12 05:42
Yeah, I'm good with that. For now, let's just add debouncing

**Comment by aklinker1** [comment] 2024-09-12 13:05
I prefer unjs packages: https://unjs.io/packages/perfect-debounce

But if there's already another as a sub dependency, we can use that one too

**Comment by 1natsu172** [comment] 2024-09-14 04:55
@kazu-ux We are working on PR for this issue. For reference, we would like to know how many seconds the reload actually takes, so please help us out.

The following patch will give you the seconds for reloading.

```diff
diff --git a/packages/wxt/dist/core/create-server.mjs b/packages/wxt/dist/core/create-server.mjs
index d74a536..239f099 100644
--- a/packages/wxt/dist/core/create-server.mjs
+++ b/packages/wxt/dist/core/create-server.mjs
@@ -19,6 +19,7 @@ import {
   getContentScriptJs,
   mapWxtOptionsToRegisteredContentScript
 } from "./utils/content-scripts.mjs";
+import { formatDuration } from "./utils/time.mjs";
 export async function createServer(inlineConfig) {
   await registerWxt("serve", inlineConfig, async (config) => {
     const { port, hostname } = config.dev.server;
@@ -92,7 +93,16 @@ export async function createServer(inlineConfig) {
     reloadContentScripts(server.currentOutput.steps, server);
   });
   const reloadOnChange = createFileReloader(server);
-  server.watcher.on("all", reloadOnChange);
+  let prev = Date.now();
+  const timerlog = () => {
+    const now = Date.now();
+    console.log(formatDuration(now - prev));
+    prev = now;
+  };
+  server.watcher.on("all", (...args) => {
+    timerlog();
+    reloadOnChange(...args);
+  });
   return server;
 }
 function createFileReloader(server) {
```

**Comment by kazu-ux** [comment] 2024-09-14 06:42
> @kazu-ux We are working on PR for this issue. For reference, we would like to know how many seconds the reload actually takes, so please help us out.
> 
> The following patch will give you the seconds for reloading.
> 
> ```diff
> diff --git a/packages/wxt/dist/core/create-server.mjs b/packages/wxt/dist/core/create-server.mjs
> index d74a536..239f099 100644
> --- a/packages/wxt/dist/core/create-server.mjs
> +++ b/packages/wxt/dist/core/create-server.mjs
> @@ -19,6 +19,7 @@ import {
>    getContentScriptJs,
>    mapWxtOptionsToRegisteredContentScript
>  } from "./utils/content-scripts.mjs";
> +import { formatDuration } from "./utils/time.mjs";
>  export async function createServer(inlineConfig) {
>    await registerWxt("serve", inlineConfig, async (config) => {
>      const { port, hostname } = config.dev.server;
> @@ -92,7 +93,16 @@ export async function createServer(inlineConfig) {
>      reloadContentScripts(server.currentOutput.steps, server);
>    });
>    const reloadOnChange = createFileReloader(server);
> -  server.watcher.on("all", reloadOnChange);
> +  let prev = Date.now();
> +  const timerlog = () => {
> +    const now = Date.now();
> +    console.log(formatDuration(now - prev));
> +    prev = now;
> +  };
> +  server.watcher.on("all", (...args) => {
> +    timerlog();
> +    reloadOnChange(...args);
> +  });
>    return server;
>  }
>  function createFileReloader(server) {
> ```

<img width="696" alt="image" src="https://github.com/user-attachments/assets/1a88d673-57be-417a-a6af-d8b86be11a5b">

I patched the code.

**Comment by 1natsu172** [comment] 2024-09-14 13:06
@kazu-ux @pnd280 Thanks both. Hmm It is taking longer than thought. About 800ms max.... I found it helpful. I'll keep you posted on any progress!

**Comment by aklinker1** [comment] 2024-09-18 13:10
Chokidor v4 just got dropped: https://github.com/paulmillr/chokidar/releases/tag/4.0.0

But we'll probably have to wait for Vite 6 before using it

**Comment by kazu-ux** [comment] 2024-09-24 11:38
I updated wxt to 0.19.10, the issue was resolved. Thank you!

**Comment by 1natsu172** [comment] 2024-09-24 11:58
@kazu-ux Oh sorry, I forgot to tell you that it's released. Glad to hear it has been resolved! (cc: @pnd280).

Can adjust it by environment variable.
> https://github.com/wxt-dev/wxt/blob/efcb593718edf9c648c6dd4876f23a180097550e/packages/wxt/src/types.ts#L1280-L1298

**Comment by aklinker1** [comment] 2024-09-26 01:57
Gonna go ahead and close this as completed!

**Closed** 2024-09-26 01:57 UTC
Labels: bug
